<a href="https://colab.research.google.com/github/Valementajat/PageRank_colab/blob/master/pageRank.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
pip install kaggle

In [2]:
import os
os.environ['KAGGLE_USERNAME'] = "johannestakamki"
os.environ['KAGGLE_KEY'] = "KGAT_3f821097959746ff4db1bbb5db1fa0f9"
!kaggle datasets download -d  benjaminawd/new-york-times-articles-comments-2020


Dataset URL: https://www.kaggle.com/datasets/benjaminawd/new-york-times-articles-comments-2020
License(s): CC-BY-NC-SA-4.0
 99% 1.93G/1.95G [00:26<00:00, 67.4MB/s]
100% 1.95G/1.95G [00:26<00:00, 79.6MB/s]


In [3]:
# Unzip the file independenty
!unzip new-york-times-articles-comments-2020.zip

Archive:  new-york-times-articles-comments-2020.zip
  inflating: nyt-articles-2020.csv   
  inflating: nyt-comments-2020.csv   
  inflating: nyt-comments-part0.csv  
  inflating: nyt-comments-part1.csv  
  inflating: nyt-comments-part2.csv  
  inflating: nyt-comments-part3.csv  
  inflating: nyt-comments-part4.csv  
  inflating: nyt-comments-part5.csv  
  inflating: nyt-comments-part6.csv  
  inflating: nyt-comments-part7.csv  
  inflating: nyt-comments-part8.csv  
  inflating: nyt-comments-part9.csv  
  inflating: test.csv                
  inflating: train.csv               


In [2]:
import numpy as np
import pandas as pd


In [3]:
df_articles = pd.read_csv("nyt-articles-2020.csv")

''' df_comments = pd.read_csv("nyt-comments-2020.csv")
 '''
''' print(df.shape) '''

' print(df.shape) '

In [9]:
for i in range(1):
    print(df_articles.iloc[i])
    ''' print(df_comments.iloc[i]) '''

print(df_articles.shape[0])

newsdesk                                              Editorial
section                                                 Opinion
subsection                                                  NaN
material                                              Editorial
headline                            Protect Veterans From Fraud
abstract      Congress could do much more to protect America...
keywords      ['Veterans', 'For-Profit Schools', 'Financial ...
word_count                                                  680
pub_date                              2020-01-01 00:18:54+00:00
n_comments                                                  186
uniqueID      nyt://article/69a7090b-9f36-569e-b5ab-b0ba5bb3...
Name: 0, dtype: object
16787


In [10]:
# Lets create the dataset we want to work from the articles
workDataSet = df_articles.sample(frac=0.2, random_state=1)


In [7]:
# Incase I want to clear the matrix for some reason
adjencencyMatrix = []

In [49]:
# Extracting unique IDs
ids = workDataSet["uniqueID"].tolist()
n = len(ids)

# Lets map what Uid is what index just in case
id_to_i = {uid: i for i, uid in enumerate(ids)}
print(id_to_i)

{'nyt://article/91a492ba-f7b3-5989-a517-3a568edad096': 0, 'nyt://article/ace5bd4e-a6a2-5fd6-adbe-33999b1f2681': 1, 'nyt://article/3f146af4-f3c9-5cc7-975c-27ba8bae981d': 2, 'nyt://article/00ff0943-553d-5afe-b98a-0fba5d736efe': 3, 'nyt://article/4aba3ab3-5684-5e40-93a1-01fc1e979e25': 4, 'nyt://article/17b76b5f-efca-588b-b2c5-3851f159febe': 5, 'nyt://article/84101427-ea09-5747-93dc-01b58d05354e': 6, 'nyt://article/1e46e3c6-8969-519a-9451-51e588736f53': 7, 'nyt://article/eab1cf16-1a31-58c1-b482-44fc49ccfde1': 8, 'nyt://article/1ab820fb-57cd-5076-a862-aa5c3d825138': 9, 'nyt://article/8887875c-9dcb-5224-bf0a-a5969a460eed': 10, 'nyt://article/d477c53e-7651-5f8a-a9a4-5ced6f193369': 11, 'nyt://article/1e4498b5-1eea-512b-b600-dcf10ce40dcb': 12, 'nyt://article/7feddc2f-2ffa-50f6-9210-e22a17da2f2d': 13, 'nyt://article/ec12018a-d5a1-5898-aa8e-e8f91b58ff6b': 14, 'nyt://article/6a632f21-0c8d-55e2-8bc4-b5955392660c': 15, 'nyt://article/4eeb67e9-22db-54bd-be2c-2cfae14d514a': 16, 'nyt://article/f47fe0d1

In [46]:
# Creating an empty adjancency matrix
adjencencyMatrix =  np.zeros((n, n ), dtype=int)



In [47]:
print(adjencencyMatrix)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


0
[0 0 0 ... 0 0 0]


In [58]:


# drop unnecessary article data from the memory to make space for the comments
# as we don't need them anymore
if 'df_articles' in locals():
    del df_articles

if 'workDataSet' in locals():
    del workDataSet


import gc
gc.collect()

0

In [ ]:
df_comments = pd.read_csv("nyt-comments-2020.csv")
for i in range(1):
    print(df_comments.iloc[i])

print(df_comments.shape[0])